#GENERIQUE

cama_influs_homepage:
    path:     /
    defaults: { _controller: CamaInflusBundle:Get:access }

error:
    path:     /error
    defaults: { _controller: CamaInflusBundle:Get:error }

access:
    path:     /access
    defaults: { _controller: CamaInflusBundle:Get:access }

phpbbreceive:
    path:     /phpbbreceive
    defaults: { _controller: CamaInflusBundle:Post:phpbbreceive }
    
# TOURS

creerTour:
    path:     /date/creer
    defaults: { _controller: CamaInflusBundle:Tour:creer }
    requirements:
         _method:  GET|POST

editerTour:
    path:     /date/{id}/editer
    defaults: { _controller: CamaInflusBundle:Tour:editer }
    requirements:
         _method:  GET|POST

supprimerTour:
    path:     /date/{id}/supprimer
    defaults: { _controller: CamaInflusBundle:Tour:supprimer }
    requirements:
         _method:  GET

ancienTour:
    path:     /date/anciens
    defaults: { _controller: CamaInflusBundle:Tour:ancien}
    requirements:
         _method:  GET

listerTour:
    path:     /date/lister
    defaults: { _controller: CamaInflusBundle:Tour:lister }
    requirements:
         _method:  GET

# PERSOS

voirMonPerso:
    path:    /perso/voir/
    defaults: { _controller: CamaInflusBundle:Perso:voirMonPerso }
    requirements:
         _method:  GET

voirPerso:
    path:    /perso/{id}/voir
    defaults: { _controller: CamaInflusBundle:Perso:voir }
    requirements:
         _method:  GET

creerPerso:
    path:    /perso/creer
    defaults: { _controller: CamaInflusBundle:Perso:creer }
    requirements:
         _method:  GET|POST

editerPerso:
    path:    /perso/{id}/editer
    defaults: { _controller: CamaInflusBundle:Perso:editer }
    requirements:
         _method:  GET|POST

validerPerso:
    path:    /perso/{id}/valider
    defaults: { _controller: CamaInflusBundle:Perso:valider }
    requirements:
         _method:  GET

devaliderPerso:
    path:    /perso/{id}/devalider
    defaults: { _controller: CamaInflusBundle:Perso:devalider }
    requirements:
         _method:  GET

listeAValiderPerso:
    path:    /perso/a_valider/liste
    defaults: { _controller: CamaInflusBundle:Perso:avalider }
    requirements:
         _method:  GET

listePerso:
    path:    /perso/lister
    defaults: { _controller: CamaInflusBundle:Perso:lister }
    requirements:
         _method:  GET
# IA
listerPNJ:
  path:    /pnj/lister
  defaults: { _controller: CamaInflusBundle:Pnj:lister}
  requirements:
         _method:  GET
creerPNJ:
  path:    /pnj/creer
  defaults: { _controller: CamaInflusBundle:Pnj:creer}
  requirements:
         _method:  GET|POST
         
voirPNJ:
  path:    /pnj/{id}/voir
  defaults: { _controller: CamaInflusBundle:Pnj:voir}
  requirements:
         _method:  GET
editerPNJ:
  path:    /pnj/{id}/editer
  defaults: { _controller: CamaInflusBundle:Pnj:editer}
  requirements:
         _method:  GET|POST
         
supprimerPNJ:
  path:    /pnj/{id}/supprimer
  defaults: { _controller: CamaInflusBundle:Pnj:supprimer}
  requirements:
         _method:  GET
         

#FICHES D'INTERPARTIE
listerFiche:
    path:     /interpartie/lister
    defaults: { _controller: CamaInflusBundle:Fiche:lister }
     requirements:
         _method:  GET
repondreFiche:
    path:     /interpartie/{id}/repondre
    defaults: { _controller: CamaInflusBundle:Fiche:repondre }
     requirements:
         _method:  GET
voirFiche:
    path:     /interpartie/courant/voir
    defaults: { _controller: CamaInflusBundle:Fiche:voir }
     requirements:
         _method:  GET
listerAncien:
    path:     /interpartie/ancien/lister
    defaults: { _controller: CamaInflusBundle:Fiche:ancien }
     requirements:
         _method:  GET
parcourirFiche:
    path:     /interpartie/{id}/voir
    defaults: { _controller: CamaInflusBundle:Fiche:parcourir }
     requirements:
         _method:  GET
         
# ORDRES 

ordres_actuels:
    path:     /ordresActuels
    defaults: { _controller: CamaInflusBundle:Get:ordresActuels }

ordres_precedents:
    path:     /ordresPrecedents
    defaults: { _controller: CamaInflusBundle:Get:ordresPrecedents }

editer_tours:
    path:     /editerTours
    defaults: { _controller: CamaInflusBundle:Get:editerTours }

