Influence:
    type: entity
    table: influence
    indexes:
        possesseur:
            columns:
                - possesseur
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 255
            fixed: false
        niveau:
            type: smallint
            nullable: false
            unsigned: true
        xp:
            type: smallint
            nullable: false
            unsigned: true
            column: XP
        ville:
            type: string
            nullable: false
            length: 255
            fixed: false
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
    manyToOne:
        possesseur:
            targetEntity: Possesseur
            cascade: {  }
            inversedBy: influences
            joinColumns:
                possesseur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
