Vehicule:
    type: entity
    table: vehicule
    indexes:
        possesseur:
            columns:
                - possesseur
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        niveau:
            type: smallint
            nullable: false
            unsigned: true
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        description:
            type: text
            nullable: false
            length: null
            fixed: false
    manyToOne:
        possesseur:
            targetEntity: Possesseur
            cascade: {  }
            inversedBy: vehicules
            joinColumns:
                possesseur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
